#!/usr/bin/env bash
# display information about subdomains
fetch_dns_info ()
{
	# Function to fetch dns info
	local domain="$1"
	local subdomain="$2"

	# If subdomain is not provided, use the default subdomains
	if [ -z "$subdomain" ];
	then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "${subdomains[@]}";
	do
		dns_info=$(dig "$sub"."$domain" | grep -A1 'ANSWER SECTION:' | grep "$domain" | awk '{print $5}')
		record_type=$(dig "$sub"."$domain" | grep -A1 'ANSWER SECTION:' | grep "$domain" | awk '{print $4}')
		echo "The subdomain $sub is a $record_type record and points to $dns_info"
	done
}

# Check if both domain and subdomain parameters are provided
if [ "$#" -eq 2 ];
then
	fetch_dns_info "$1" "$2"
else
	fetch_dns_info "$1"
fi
