#!/usr/bin/env bash
# transfers a file from our client to a server.
if [ "$1" ] && [ "$2" ] && [ "$3" ];
then
	if [ "$4" ];
	then
		scp -o "StrictHostKeyChecking no" -i "$4" "$1" "$3"@"$2":~/
	else
		scp -o "StrictHostKeyChecking no" "$1" "$3"@"$2":~/
	fi
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
