#!/usr/bin/env bash
# Install and configure HAproxy
apt-get -y update
apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cfg="
backend web-backend
	balance roundrobin
	server web-01 54.208.56.50:80
        server web-02 54.90.5.188:80

frontend http
        bind *:80
        mode http
        default_backend web-backend
"
echo "$cfg" >> /etc/haproxy/haproxy.cfg
service haproxy restart
