#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
systemctl stop nginx
apt-get purge nginx
apt-get autoremove
rm -rf /etc/nginx /var/log/nginx
apt-get -y update
apt-get -y install nginx
service nginx restart
