#!/usr/bin/env bash
# displays To infinity and beyond
# and I am invincible!!! when receiving a SIGTERM signal
trap 'echo I am invincible!!!' TERM
while :
do
        echo To infinity and beyond
        sleep 2
done
