#!/usr/bin/env bash
# FizzBuzz
for i in {1..100}
do
	((rem5=$i%5))
	((rem3=$i%3))
	if [ "$rem5" = 0 ] && [ "$rem3" = 0 ]
	then
		echo FizzBuzz
	elif [ "$rem5" = 0 ]
	then
		echo Buzz
	elif [ "$rem3" = 0 ]
	then
		echo Fizz
	else
		echo "$i"
	fi
done
