#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
((hour=0))
((min=1))
while [ "$hour" != 13 ]
	do if [ "$min" = 1 ]
		then echo "Hour:" $hour
		fi
	echo $min
	((min=min+1))
	if [ "$min" = 60 ]
		then ((min=1))
		((hour=hour+1))
		fi
done
