#!/usr/bin/env bash
# displays the content of the current directory
# where only the part of the name after the first dash is displayed
list="$(ls)"
for item in $list
	do echo $item | cut -d- -f2
done
