#!/usr/bin/env bash
# get Apache to run on the container
# and to return a page containing Hello Holberton
apt update -y
apt install apache2 -y
echo "Hello Holberton" > /var/www/html/index.html
service apache2 restart
