#!/usr/bin/env bash
# configures the container
chmod 244 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
